// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Creator, CreatorTableId } from "./tables/Creator.sol";
import { Timezone, TimezoneTableId } from "./tables/Timezone.sol";
import { Expiration, ExpirationTableId } from "./tables/Expiration.sol";
import { StartTime, StartTimeTableId } from "./tables/StartTime.sol";
import { DaysOfWeek, DaysOfWeekTableId } from "./tables/DaysOfWeek.sol";
import { WakeupObjective, WakeupObjectiveTableId } from "./tables/WakeupObjective.sol";
import { BaseReward, BaseRewardTableId } from "./tables/BaseReward.sol";
import { AlarmTime, AlarmTimeTableId } from "./tables/AlarmTime.sol";
import { Suns, SunsTableId } from "./tables/Suns.sol";
import { Level, LevelTableId } from "./tables/Level.sol";
import { WakeupChallengeType, WakeupChallengeTypeTableId } from "./tables/WakeupChallengeType.sol";
import { TargetWakeupObjective, TargetWakeupObjectiveTableId } from "./tables/TargetWakeupObjective.sol";
import { ChallengeStatus, ChallengeStatusTableId } from "./tables/ChallengeStatus.sol";
import { SunsStaked, SunsStakedTableId } from "./tables/SunsStaked.sol";
import { EthStaked, EthStakedTableId } from "./tables/EthStaked.sol";
import { WakeupConfirmations, WakeupConfirmationsTableId } from "./tables/WakeupConfirmations.sol";
import { SubmissionWindow, SubmissionWindowTableId } from "./tables/SubmissionWindow.sol";
import { AlarmSchedule, AlarmScheduleData, AlarmScheduleTableId } from "./tables/AlarmSchedule.sol";
import { TimezoneAttested, TimezoneAttestedTableId } from "./tables/TimezoneAttested.sol";
