// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { WakeupObjectives, WakeupObjectivesTableId } from "./tables/WakeupObjectives.sol";
import { Creator, CreatorTableId } from "./tables/Creator.sol";
import { AlarmTime, AlarmTimeTableId } from "./tables/AlarmTime.sol";
import { Timezone, TimezoneTableId } from "./tables/Timezone.sol";
import { WakeupConfirmations, WakeupConfirmationsTableId } from "./tables/WakeupConfirmations.sol";
import { Credit, CreditTableId } from "./tables/Credit.sol";
