// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAlarmScheduleSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAlarmScheduleSystem {
  function newAlarmSchedule(
    bytes32 entity,
    uint32 alarmTime,
    uint32 submissionWindow,
    int8 timezoneOffsetHrs,
    uint32 expiration,
    uint8[] memory alarmDays
  ) external;

  function recordEntry(bytes32 entity) external;

  function inSubmissionWindow(bytes32 entity) external view returns (bool);

  function expired(bytes32 entity) external view returns (bool);
}
