// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IDailyCheckinChallengeSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDailyCheckinChallengeSystem {
  function enter(bytes32 wakeupObjective, uint numWeeks, uint8[] memory challengeDays) external returns (uint32);
}
